### ISSUE TITLE
Question about deepglobe dataset

### ISSUE THREAD

**Issue by canglangzhige** [slei109/PATNet#17]
Thanks for your work!
I have some questions about deepglobe daaset:

1.Your got 5666 deepglobe images after filtering the single class images and the ‘unknown’ class. As stated in your paper.
   But I got 9174 images follows the preprocess.py. Why is it? Will this have an impact on the results?
2. It seems that you cut each image into 36 pieces but not 6 pieces.
3. It seems that the preprocess.py is Incomplete. 
    When test the model, we need datapath like `ann_path = os.path.join(self.base_path, query_name.split('/')[-4], 'test', 'groundtruth')` or `img_paths = sorted([path for path in glob.glob('%s/*' % os.path.join(self.base_path, cat, 'test', 'origin'))])`. But there are no paths like 'test', 'origin' or 'groundtruth' in the script preprocess.py. What should I do here?

Thanks!

**Comment by slei109** [comment]
1. I have no idea about what happens. For the single class, we filter out the images whose percentage are less than 0.048 instead of 0. If most of the area in your figure belongs to one class, then your performance are expected to be higher.
2. Yes, you are right. We cut each image into 36 pieces.
3. Here, "groundtruth" is the name for mask folder, and "origin" is the name for image folder. You can use your own datapath, so the folder name doesn't matter.
