### ISSUE TITLE
Question about random seeds

### ISSUE THREAD

**Issue by canglangzhige** [slei109/PATNet#23]
非常感谢您将工作开源！

在paper中您写道 “For each evaluation, we average the mean-IoU of 5 runs [44] with different random seeds.”
但是 test.py 代码中固定了 seed：utils.fix_randseed(0)
请问5次结果是怎样得到的？是将 utils.fix_randseed(0)->utils.fix_randseed(None)，然后运行5遍test.py 吗？

**Comment by canglangzhige** [comment]
另外，我之前问过一个问题[https://github.com/slei109/PATNet/issues/13](url)

我重新在一块 RTX 5000 显卡上运行，batch_size = 12, 占用13653MiB内存，保存的权重文件为112.9M。但是我仍然需要1个小时才能完成一个epoch，这太奇怪了。而运行HSNet只需要十几分钟。

我看到您的工作是基于HSNet，我将 patnet.py 放入 HSNet 代码中进行训练，仍然需要将近1个小时。

**Comment by canglangzhige** [comment]
我在使用5shot训练的时候，出现如下问题（batch_size = 2）
RuntimeError: Expected 4-dimensional input for 4-dimensional weight [64, 3, 7, 7], but got 5-dimensional input of size [2, 5, 3, 400, 400] instead.

在代码 train.py 中看到 `logit_mask = model(batch['query_img'], batch['support_imgs'].squeeze(1), batch['support_masks'].squeeze(1))`
对于1shot来说，第（1）维为1，可以被压缩，但是对于5shot，使用squeeze(1)并不能把这个纬度压缩，导致了tensor纬度不对。请问此处具体是怎样处理的？

**Comment by slei109** [comment]
- Yes, remove the seed and run the testing five times, and then average the results.
- Not sure what's the problem. I can finish one epoch within 10 minutes on one 3090 GPU. I'm wondering if it might be due to different environmental settings, because no one else has reported this issue.
- There's no special thing for 5-shot training compared with 1-shot setting. You don't need to retrain the model. Same as Hsnet, for the 5-shot setting, the model performs 5 forward passes to provide a set of 5 mask predictions. We perform voting at every pixel location by summing all the 5 predictions and dividing each output score by the maximum voting
score.
