### ISSUE TITLE
About the transformation

### ISSUE THREAD

**Issue by King-king424** [slei109/PATNet#35]
I find that using the transformation that you proposed would make model convergence much slower.
I wonder why and do you think there is any way to accelerate model convergence when I try to integrate the transformation module into a fss model.

**Comment by King-king424** [comment]
Looking forward to your reply.
Thanks.

**Comment by slei109** [comment]
Thanks for creating this discussion. Yep, it will be a bit slow because it requires extra computational steps to get the transformation matrix W. It takes an extra two to three training hours on the single 3090 GPU card, which is tolerable for me. If you want to accelerate the model, you could find out if there's a way to parallelize the calculation of the generalized inverse.
